/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

export const API_ENDPOINT =
	"https://g9yh14f7ve.execute-api.ap-south-1.amazonaws.com/Authorizeddev";

export const APP_CLIENT_ID = "42kuh6q6musktac4venofg0tjk";

export const config = {
	API: {
		endpoints: [
			{
				name: "BankApprovalApi",

				endpoint: API_ENDPOINT,
			},
		],
	},

	Auth: {
		// REQUIRED - Amazon Cognito Region

		region: "ap-south-1",

		// OPTIONAL - Amazon Cognito Federated Identity Pool Region

		// Required only if it's different from Amazon Cognito Region

		identityPoolRegion: "ap-south-1",

		// OPTIONAL - Amazon Cognito User Pool ID

		userPoolId: "ap-south-1_hEjaz8gqs",

		// OPTIONAL - Amazon Cognito Web Client ID (26-char alphanumeric string)

		userPoolWebClientId: APP_CLIENT_ID,

		// OPTIONAL - Enforce user authentication prior to accessing AWS resources or not

		mandatorySignIn: true,

		// OPTIONAL - Manually set the authentication flow type. Default is 'USER_SRP_AUTH'

		authenticationFlowType: "USER_SRP_AUTH",

		// OPTIONAL - Manually set key value pairs that can be passed to Cognito Lambda Triggers

		clientMetadata: { myCustomKey: "myCustomValue" },

		// OPTIONAL - Hosted UI configuration

		oauth: {
			domain: "banker.auth.ap-south-1.amazoncognito.com",

			scope: ["email", "openid"],

			redirectSignIn: "https://master.d1q0czh86hkdgz.amplifyapp.com/",

			logoutUri: "https://master.d1q0czh86hkdgz.amplifyapp.com/",

			redirectUri: "https://master.d1q0czh86hkdgz.amplifyapp.com/",

			redirectSignOut: "https://master.d1q0czh86hkdgz.amplifyapp.com/",

			responseType: "token", // or 'token', note that REFRESH token will only be generated when the responseType is code
		},
	},
};

const awsmobile = {
	aws_project_region: "ap-south-1",
	aws_cognito_identity_pool_id:
		"ap-south-1:f06d6b8d-8490-40d9-922d-0417a9f3eb7c",
	aws_cognito_region: "ap-south-1",
	aws_user_pools_id: "ap-south-1_hEjaz8gqs",
	aws_user_pools_web_client_id: "5e1rauvsded6cepsrl3f56tmfr",
	oauth: {},
	aws_cognito_login_mechanisms: ["EMAIL"],
	aws_cognito_signup_attributes: ["EMAIL"],
	aws_cognito_mfa_configuration: "OFF",
	aws_cognito_mfa_types: ["SMS"],
	aws_cognito_password_protection_settings: {
		passwordPolicyMinLength: 8,
		passwordPolicyCharacters: [],
	},
};

export default awsmobile;
